[2025-08-19T11:00:27.848+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-19T11:00:27.881+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_audit_dag.final_status_task scheduled__2025-08-19T10:00:00+00:00 [queued]>
[2025-08-19T11:00:27.895+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_audit_dag.final_status_task scheduled__2025-08-19T10:00:00+00:00 [queued]>
[2025-08-19T11:00:27.904+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-19T11:00:27.924+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): final_status_task> on 2025-08-19 10:00:00+00:00
[2025-08-19T11:00:27.938+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=978) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-19T11:00:27.943+0000] {standard_task_runner.py:63} INFO - Started process 987 to run task
[2025-08-19T11:00:27.944+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_audit_dag', 'final_status_task', 'scheduled__2025-08-19T10:00:00+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/Assessment_2/data_audit_dag.py', '--cfg-path', '/tmp/tmpmtwd4fg8']
[2025-08-19T11:00:27.955+0000] {standard_task_runner.py:91} INFO - Job 61: Subtask final_status_task
[2025-08-19T11:00:28.099+0000] {task_command.py:426} INFO - Running <TaskInstance: data_audit_dag.final_status_task scheduled__2025-08-19T10:00:00+00:00 [running]> on host 37fc8edea13d
[2025-08-19T11:00:28.268+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='youremail@example.com' AIRFLOW_CTX_DAG_OWNER='rajpriya' AIRFLOW_CTX_DAG_ID='data_audit_dag' AIRFLOW_CTX_TASK_ID='final_status_task' AIRFLOW_CTX_EXECUTION_DATE='2025-08-19T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-19T10:00:00+00:00'
[2025-08-19T11:00:28.274+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-19T11:00:28.275+0000] {logging_mixin.py:188} INFO - [Final]  Audit Success for user: 101
[2025-08-19T11:00:28.276+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-08-19T11:00:28.277+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-19T11:00:28.293+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_audit_dag, task_id=final_status_task, run_id=scheduled__2025-08-19T10:00:00+00:00, execution_date=20250819T100000, start_date=20250819T110027, end_date=20250819T110028
[2025-08-19T11:00:28.364+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-19T11:00:28.386+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
