[2025-08-19T10:41:02.316+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-19T10:41:02.354+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_audit_dag.bash_notify_task scheduled__2025-08-19T09:00:00+00:00 [queued]>
[2025-08-19T10:41:02.373+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_audit_dag.bash_notify_task scheduled__2025-08-19T09:00:00+00:00 [queued]>
[2025-08-19T10:41:02.375+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-19T10:41:02.405+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): bash_notify_task> on 2025-08-19 09:00:00+00:00
[2025-08-19T10:41:02.445+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=734) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-19T10:41:02.450+0000] {standard_task_runner.py:63} INFO - Started process 739 to run task
[2025-08-19T10:41:02.450+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_audit_dag', 'bash_notify_task', 'scheduled__2025-08-19T09:00:00+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/Assessment_2/data_audit_dag.py', '--cfg-path', '/tmp/tmp_mbrqh94']
[2025-08-19T10:41:02.459+0000] {standard_task_runner.py:91} INFO - Job 56: Subtask bash_notify_task
[2025-08-19T10:41:02.582+0000] {task_command.py:426} INFO - Running <TaskInstance: data_audit_dag.bash_notify_task scheduled__2025-08-19T09:00:00+00:00 [running]> on host 37fc8edea13d
[2025-08-19T10:41:02.727+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='youremail@example.com' AIRFLOW_CTX_DAG_OWNER='rajpriya' AIRFLOW_CTX_DAG_ID='data_audit_dag' AIRFLOW_CTX_TASK_ID='bash_notify_task' AIRFLOW_CTX_EXECUTION_DATE='2025-08-19T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-19T09:00:00+00:00'
[2025-08-19T10:41:02.733+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-19T10:41:02.743+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-19T10:41:02.759+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'Audit DAG run completed!'"]
[2025-08-19T10:41:02.788+0000] {subprocess.py:86} INFO - Output:
[2025-08-19T10:41:02.807+0000] {subprocess.py:93} INFO - Audit DAG run completed!
[2025-08-19T10:41:02.808+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-08-19T10:41:02.812+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-19T10:41:02.863+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_audit_dag, task_id=bash_notify_task, run_id=scheduled__2025-08-19T09:00:00+00:00, execution_date=20250819T090000, start_date=20250819T104102, end_date=20250819T104102
[2025-08-19T10:41:02.952+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-19T10:41:02.982+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-19T10:41:02.987+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
