[2025-08-19T09:39:58.050+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-19T09:39:58.114+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_audit_dag.log_results_task manual__2025-08-19T09:22:15.873297+00:00 [queued]>
[2025-08-19T09:39:58.139+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_audit_dag.log_results_task manual__2025-08-19T09:22:15.873297+00:00 [queued]>
[2025-08-19T09:39:58.140+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-08-19T09:39:58.174+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): log_results_task> on 2025-08-19 09:22:15.873297+00:00
[2025-08-19T09:39:58.221+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2292) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-19T09:39:58.227+0000] {standard_task_runner.py:63} INFO - Started process 2301 to run task
[2025-08-19T09:39:58.229+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_audit_dag', 'log_results_task', 'manual__2025-08-19T09:22:15.873297+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/Assessment_2/data_audit_dag.py', '--cfg-path', '/tmp/tmp_w0lk18c']
[2025-08-19T09:39:58.237+0000] {standard_task_runner.py:91} INFO - Job 36: Subtask log_results_task
[2025-08-19T09:39:58.432+0000] {task_command.py:426} INFO - Running <TaskInstance: data_audit_dag.log_results_task manual__2025-08-19T09:22:15.873297+00:00 [running]> on host 37fc8edea13d
[2025-08-19T09:39:58.708+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='youremail@example.com' AIRFLOW_CTX_DAG_OWNER='rajpriya' AIRFLOW_CTX_DAG_ID='data_audit_dag' AIRFLOW_CTX_TASK_ID='log_results_task' AIRFLOW_CTX_EXECUTION_DATE='2025-08-19T09:22:15.873297+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-19T09:22:15.873297+00:00'
[2025-08-19T09:39:58.715+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-19T09:39:58.721+0000] {logging_mixin.py:188} INFO - [Log] Audit Result: {'data': {'user_id': 101, 'balance': 1539, 'timestamp': '2025-08-19 09:22:46.997432'}, 'valid': True}
[2025-08-19T09:39:58.722+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-08-19T09:39:58.724+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-19T09:39:58.757+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_audit_dag, task_id=log_results_task, run_id=manual__2025-08-19T09:22:15.873297+00:00, execution_date=20250819T092215, start_date=20250819T093958, end_date=20250819T093958
[2025-08-19T09:39:58.889+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-19T09:39:58.977+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-08-19T09:39:58.982+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
